### ISSUE TITLE
How to use that??

### ISSUE THREAD

**Issue by Faloigi** [RainingChain/PkCompletionist#4]
I dont understand how to use this tool, i've tried to use it by this [site](https://scripterswar.com/pokemon/completion/Yellow) but when i put the .sav file idk why the site say:
Error: The game version of the .sav (RBY) is not YW (Yellow)

But it is a Pokemon yellow sav
PLS HELP

**Comment by RainingChain** [comment]
What version of the game exactly were you playing? Original Gameboy or 3DS remake? Can you send me the problematic .sav?

**Comment by Faloigi** [comment]
[YW.zip](https://github.com/RainingChain/PkCompletionist/files/13651883/YW.zip)
Here is my sav, sorry if i respond you late btw im playinh pokemon Yellow on gba advance emulator

**Comment by RainingChain** [comment]
> [YW.zip](https://github.com/RainingChain/PkCompletionist/files/13651883/YW.zip) Here is my sav, sorry if i respond you late btw im playinh pokemon Yellow on gba advance emulator

That save file has no pokemon. At least 1 pokemon (Pikachu) is required to detect that it's really a Yellow game. 

Alternatively, you can submit an issue at https://github.com/kwsch/PKHeX to improve the logic to recognize Yellow save files.
